




<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="AddApplication.aspx.cs" Inherits="DejaVu.SelfHealthCheck.MonitorNew.pages.AddApplication" %>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Self Health Check | Add Application</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="../bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link href="../bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

     <script src="../plugins/jQuery/jQuery-2.2.0.min.js"></script>
    <script src="../Scripts/jquery.signalR-2.0.3.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="../signalr/hubs"></script>

    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- daterange picker -->
    <link rel="stylesheet" href="../plugins/daterangepicker/daterangepicker-bs3.css">
    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="../plugins/iCheck/all.css">
    <!-- Bootstrap Color Picker -->
    <link rel="stylesheet" href="../plugins/colorpicker/bootstrap-colorpicker.min.css">
    <!-- Bootstrap time Picker -->
    <link rel="stylesheet" href="../plugins/timepicker/bootstrap-timepicker.min.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="../plugins/select2/select2.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="../dist/css/skins/_all-skins.min.css">
    <!-- include the alertify core styles -->
    <link rel="stylesheet" href="../bower_components/alertify.js-0.3.11/themes/alertify.core.css" />
    <!-- include a alertify theme, can be included into the core instead of 2 separate files -->
    <link rel="stylesheet" href="../bower_components/alertify.js-0.3.11/themes/alertify.default.css" />
    <!-- include a alertify theme, can be included into the core instead of 2 separate files -->
    <link rel="stylesheet" href="../bower_components/alertify.js-0.3.11/themes/alertify.bootstrap.css" />
    
    <script src="../Scripts/ngApp/selfCheck/monitorController.js"></script>

    <!--Form Validation -->
    <link rel="stylesheet" href="../bower_components/formvalidation-master/dist/css/formValidation.min.css">

    <!-- MY CSS-->
    <link rel="stylesheet" href="../bower_components/style.css" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

        <header class="main-header">
            <!-- Logo -->
            <a href="/index.html" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>H</b>CM</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg">Health Check Monitor</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- Control Sidebar Toggle Button -->
                        <li>
                            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    <li><a href="../index.html"><i class="fa fa-dashboard"></i><span>DashBoard</span></a></li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-folder"></i><span>Applications</span>
                            <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="AddApplication.aspx"><i class="fa fa-plus-circle"></i>Add Application</a></li>
                            <li><a href="view-applications.html"><i class="fa fa-th-list"></i>View Applications</a></li>
                        </ul>
                    </li>
                     <li>
                        <a href="healthmessages.html"><i class="fa fa-table fa-fw"></i> Health Messages</a>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-folder"></i><span>Category/Profile</span>
                            <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                        <li><a href="AddCategoryOrProfile.aspx"><i class="fa fa-plus-circle"></i>Add Category/Profile</a></li>
                        <li><a href="ViewCategoriesOrProfiles.html"><i class="fa fa-th-list"></i>View Category/Profile</a></li>
                       </ul>
                    </li>

                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>Add New Application
                </h1>
            </section>

            <!-- Main content -->
            <section class="content">

                <!-- SELECT2 EXAMPLE -->
                <div class="box box-default">
                    <div class="box-header with-border">
                        <h3 class="box-title">Set Up a new Application</h3>

                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="row">
                            <form id="mainForm" name="mainForm" method="post" role="form" runat="server">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>App Name</label>
                                        <input class="form-control" id="AppNameTxt" runat="server" name="appName" />
                                    </div>
                                    <div class="form-group">
                                        <label>Dependent Apps</label>
                                        <select id="AppsDrpDown" class="form-control" runat="server"></select>
                                    </div>
                                    <asp:Button ID="SaveButton" runat="server" type="submit" class="btn btn-default" Text="Save" OnClick="SaveButton_Click" />

                                    <!-- /.form-group -->
                                </div>
                                <!-- /.col -->
                               <%-- <div class="col-md-6">
                                    <div class="form-group">
                                        <label>App ID</label>
                                        <input class="form-control" id="AppIDTxt" runat="server" name="appID" />
                                    </div>
                                </div>--%>
                            </form>
                            <!-- /.col -->
                        </div>
                        <!-- /.row -->
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->

            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 2.3.2
   
            </div>
            <strong>Copyright &copy; <%DateTime.Now.Year.ToString();%> <a href="#">AppZone</a>.</strong> All rights reserved.
 
        </footer>

        <!-- Control Sidebar -->

        <!-- /.control-sidebar -->
        <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->

    <!-- jQuery 2.2.0 -->
    <script src="../plugins/jQuery/jQuery-2.2.0.min.js"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="../bootstrap/js/bootstrap.min.js"></script>
    <!-- Alertify 0.3.11 -->
    <script src="../bower_components/alertify.js-0.3.11/lib/alertify.min.js"></script>
    <!-- FormValidation plugin and the class supports validating Bootstrap form -->
    <script src="../bower_components/formvalidation-master/dist/js/formValidation.min.js"></script>
    <script src="../bower_components/formvalidation-master/dist/js/framework/bootstrap.min.js"></script>
    <!-- Select2 -->
    <script src="../plugins/select2/select2.full.min.js"></script>
    <!-- InputMask -->
    <script src="../plugins/input-mask/jquery.inputmask.js"></script>
    <script src="../plugins/input-mask/jquery.inputmask.date.extensions.js"></script>
    <script src="../plugins/input-mask/jquery.inputmask.extensions.js"></script>
    <!-- date-range-picker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
    <script src="../plugins/daterangepicker/daterangepicker.js"></script>
    <!-- bootstrap color picker -->
    <script src="../plugins/colorpicker/bootstrap-colorpicker.min.js"></script>
    <!-- bootstrap time picker -->
    <script src="../plugins/timepicker/bootstrap-timepicker.min.js"></script>
    <!-- SlimScroll 1.3.0 -->
    <script src="../plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- iCheck 1.0.1 -->
    <script src="../plugins/iCheck/icheck.min.js"></script>
    <!-- FastClick -->
    <script src="../plugins/fastclick/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="../dist/js/app.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="../dist/js/demo.js"></script>
    <!-- Page script -->

    <script type="text/javascript">
        $(document).ready(function () {
            $("#AppsDrpDown").select2({ placeholder: 'Find and Select Apps' });

            $('#mainForm').formValidation({
                framework: 'bootstrap',
                icon: {
                    valid: 'glyphicon glyphicon-ok',
                    invalid: 'glyphicon glyphicon-remove',
                    validating: 'glyphicon glyphicon-refresh'
                },
                fields: {
                    AppNameTxt: {
                        validators: {
                            notEmpty: {
                                message: 'An App Name is required'
                            },
                            stringLength: {
                                max: 25,
                                message: 'The App Name must be less than 25 characters long'
                            },
                        }
                    },
                    //AppIDTxt: {
                    //    validators: {
                    //        notEmpty: {
                    //            message: 'An App ID is required'
                    //        },
                    //        regexp: {
                    //            regexp: /^[a-zA-Z0-9_\.\-]+$/,
                    //            message: 'The App ID can only consist of alphabetical, number, dot,dash and underscore'
                    //        }
                    //    }
                    //}
                }
            });
        });

    </script>

    <script type="text/javascript">

        function showNotification(isSuccess, message, redirectUrl) {

            if (isSuccess == 'True') {
                alertify.alert(message, function (e) {
                    if (e) {
                        // user clicked "ok"
                        window.location = redirectUrl;
                    }
                }, 'success');
            }
            else {

                alertify.alert(message, function (e) {
                    if (e) {
                        // user clicked "ok"
                        window.location = redirectUrl;
                    }
                }, 'error');
            }return false;
        }
    </script>
</body>
</html>
